// apps/vue-demo/src/view/timer.view.vue
<!--@desc View with Store (Cannot reuse without same store)-->

<script setup lang="ts">
import TimerCom from '../gallery/timer.com.vue';
import { useTimerStore } from '../store/timer.store';
import { computed } from 'vue';

const props = defineProps({
    rate: Number,
    node: HTMLElement,
});

const tip = computed(() => (props.rate === 1 || props.rate == null ? null : `${props.rate}x`));

const timerStore = useTimerStore();
</script>

<template>
    <TimerCom :timePassed="timerStore.timePassed" :node="props.node" :tip="tip"></TimerCom>
</template>

// apps/react-demo/src/component/mobx/Timer.View.tsx
import { TimerAtom } from '../atom/Timer.Atom';
import { useStore } from '../../context';
import { observer } from 'mobx-react-lite';

interface ITimeViewProps {
    tip?: string;
    node?: HTMLElement;
}

/**
 * @desc View with Store (Cannot reuse without same store)
 */
export const TimerView = observer((props: ITimeViewProps) => {
    // App store (Mobx)
    const { timerStore } = useStore();

    return <TimerAtom timePassed={timerStore.timePassed} {...props} />;
});
