// packages/react-demo/src/gallery/timer.com.tsx
import { useEffect, useRef } from 'react';

interface ITimerComProps {
    timePassed: number;
    tip?: string;
    node?: HTMLElement;
}

/**
 * @desc Pure React Component (Can reuse in other project)
 */
export const TimerCom = (props: ITimerComProps) => {
    const ref = useRef<HTMLParagraphElement>();

    useEffect(() => {
        if (props.node) {
            ref.current.append(props.node);
            return () => props.node.remove();
        }
    }, []);

    return (
        <p ref={ref}>
            Time passed: {props.timePassed}s{props.tip ? ` (${props.tip})` : null}
        </p>
    );
};

// packages/vue-demo/src/gallery/timer.com.vue
<!--@desc Pure Vue Component (Can reuse in other project)-->

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

const props = defineProps({
    timePassed: { type: Number, required: true },
    tip: String,
    node: HTMLElement,
});

const elRef = ref<HTMLParagraphElement>(null);

onMounted(() => {
    if (props.node) {
        elRef.value.append(props.node);
    }
});

onUnmounted(() => {
    if (props.node) {
        props.node.remove();
    }
});
</script>

<template>
    <p>
        Time passed: {{ props.timePassed }}s{{ props.tip ? ` (${props.tip})` : null }}
        <span ref="elRef" v-if="props.node"></span>
    </p>
</template>
