// apps/react-demo/src/component/atom/Submit.tsx
interface ISubmitProps {
    submitted: boolean;
    onClick: () => void;
}

/**
 * @desc Pure React Component (Can reuse in other project)
 */
export function Submit({ submitted, onClick }: ISubmitProps) {
    return (
        <p>
            <button onClick={onClick} disabled={submitted}>
                Submit Button (App Level)
            </button>
        </p>
    );
}

// apps/vue-demo/src/component/atom/Submit.vue
<template>
    <p>
        <button @click="onClick" :disabled="submitted">Submit Button (App Level)</button>
    </p>
</template>

<script setup lang="ts">
import { toRefs } from 'vue';

interface IProps {
    submitted: boolean;
}

interface IEmits {
    (e: 'click'): void;
}

const props = defineProps<IProps>();
const emits = defineEmits<IEmits>();
const onClick = () => emits('click');
const { submitted } = toRefs(props);
</script>
